Dev/checkpoint base on fullnode
PaytonWu/TOP-chain pull request #109
Opened 2021-12-07 10:47 UTC by LonDong-TopNetwork

2021-12-08 03:48 UTC, PaytonWu commented on src/xtopcom/xblockstore/src/xcheckpoint.h
> +using xcheckpoint_cmp_t = xtop_checkpoint_cmp;
useless?

2021-12-08 03:50 UTC, PaytonWu requested changes

2021-12-08 03:50 UTC, PaytonWu commented on src/xtopcom/xblockstore/src/xcheckpoint.cpp
> +#endif
move these xcheckpoint_xxx.h into xcheckpoint_data/xcheckpoints.h

2021-12-09 07:36 UTC, LonDong-TopNetwork commented on src/xtopcom/xblockstore/src/xcheckpoint.h
> +using xcheckpoint_cmp_t = xtop_checkpoint_cmp;
already remove useless.

2021-12-09 07:40 UTC, LonDong-TopNetwork commented on src/xtopcom/xblockstore/src/xcheckpoint.cpp
> +#endif
finish gethering those into one file. how about put all "string literals" files in one module, such as genesis info, reset data and checkpoint data.

2021-12-09 09:24 UTC, PaytonWu approved these changes

2021-12-09 09:24 UTC, merged